### ISSUE TITLE
Extract paths to constant or variables

### ISSUE THREAD

**Issue by codebjorn** [bastinald/laravel-automatic-migrations#2]
https://github.com/bastinald/laravel-automatic-migrations/blob/31d26e9ab35e41d25692524fd32b8ff92f7959fc/src/Providers/LaravelAutomaticMigrationsProvider.php#L23

First hi, I want to say that is very interesting project.
Here on publish I see that multiple times are used same paths:
```php
'/../../config'
'/../../resources'
```

**As a purpose** maybe will be better to extract them to variables or constants(if will be used on other classes), as example:
```php
$configPath = __DIR__ . '/../../config';
$resourcesPath = __DIR__ . '/../../resources';
```
or in class
```php
const CONFIG_PATH = __DIR__ . '/../../config';
const RESOURCES_PATH = __DIR__ . '/../../resources';
```
and usage will be
```php
 $this->publishes(
            ["{$configPath}/laravel-automatic-migrations.php" => config_path('laravel-automatic-migrations.php')],
 ...
```
or
```php
 $this->publishes(
            [CONFIG_PATH  . '/laravel-automatic-migrations.php' => config_path('laravel-automatic-migrations.php')],
 ...
```

**Comment by bastinald** [comment]
Those strings are only used once inside the service provider to tell Laravel where to publish the files if someone chooses to do so via the `vendor:publish` command.

**Comment by codebjorn** [comment]
Well you can use
